### ISSUE TITLE
Uncaught Exception: Error: ECONNRESET

### ISSUE THREAD

**Issue by dimanjy** [song940/socks-proxy#1]
Hi! Thanks for great module. It works great, but I got an issue:

> Uncaught Exception:
> Error: read ECONNRESET
>     at _errnoException (util.js:1024:11)
>     at TCP.onread (net.js:615:25)

I'm starting a local Socks proxy (127.0.0.1:1080) and change Firefox settings to use this local server as Socks 5 proxy.
And when I press STOP button in Firefox while page loading, then server throws an above exception.

**Comment by dimanjy** [comment]
Also I got another error while browsing through the local socks proxy:

> Uncaught Exception:
> Error: connect ECONNREFUSED 54.192.98.51:443
>    at Object._errnoException (util.js:1024:11)
>    at _exceptionWithHostPort (util.js:1046:20)
>    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by dimanjy** [comment]
I just found a problem. Its in default `proxy` method of `Server` class.

The source:

```javascript
  /**
   * default proxy handler
   * @param {*} client 
   */
  proxy(client) {
    const {
      address,
      port
    } = client.request;
    tcp.connect(port, address, function (err) {
      client.reply(0);
      client.pipe(this).pipe(client);
    });
  }
```

I changed to:
```javascript
proxy(client) {
        const { address, port } = client.request;
        var conn = net.connect(port, address, function (err) {
            client.reply(0);
            client.pipe(this).pipe(client);
        });
        conn.on('error', (e)=>{ /* Catch errors here! */ });
    }
```

**Comment by lsongdev** [comment]
Any questions?
